// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.PodcastMgt.PowerTools.Models;

public partial class Machine
{
    public string Id { get; set; }

    public bool IsUsable { get; set; }

    public string Note { get; set; }

    public string TargetDrive { get; set; }

    public virtual ICollection<Feed> Feeds { get; set; } = new List<Feed>();
}