global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.IO.IsolatedStorage;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Runtime.Serialization.Json;
global using System.Text;
global using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using System.Threading;
global using System.Threading.Tasks;
global using System.Xml;
global using System.Xml.Serialization;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
//global using Serilog;
global using StandardLib.Extensions;
global using StandardLib.Helpers;
global using static System.Diagnostics.Trace;
